version: 2.1

executors:
  circle-jdk-executor:
    working_directory: ~/app
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    docker:
      - image: cimg/openjdk:13.0
    steps:
  machine-executor:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202008-01


jobs:
  build:
    executor: machine-executor
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Setup
          command: |
            docker run -d -p 5431:5432 -e POSTGRES_DB=wb_test -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=test_pass
            sleep 5
      - run: gradle test

